name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Build binaries
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/webpanel-linux-amd64
            release/webpanel-linux-386
            release/webpanel-linux-arm-v6
            release/webpanel-linux-arm-v7
            release/webpanel-linux-arm64
            release/webpanel-linux-amd64.sha256
            release/webpanel-linux-386.sha256
            release/webpanel-linux-arm-v6.sha256
            release/webpanel-linux-arm-v7.sha256
            release/webpanel-linux-arm64.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}