name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0.0, v1.2.3
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, 386, arm, arm64]
        goarm: ['', 6, 7] # goarm only apply for arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true # Enable caching
          cache-dependency-path: go.sum

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
        run: |
          mkdir -p bin

          # Handle arm special cases
          if [ "${{ matrix.goarch }}" = "arm" ]; then
            if [ "${{ matrix.goarm }}" = "6" ]; then
              BINARY_NAME="webpanel-linux-arm-v6"
            elif [ "${{ matrix.goarm }}" = "7" ]; then
              BINARY_NAME="webpanel-linux-arm-v7"
            else
              echo "Invalid GOARM value for arm architecture"
              exit 1
            fi
          elif [ "${{ matrix.goarch }}" = "amd64" ]; then
            BINARY_NAME="webpanel-linux-amd64"
          elif [ "${{ matrix.goarch }}" = "386" ]; then
            BINARY_NAME="webpanel-linux-386"
          elif [ "${{ matrix.goarch }}" = "arm64" ]; then
            BINARY_NAME="webpanel-linux-arm64"
          else
            echo "Invalid GOARCH value"
            exit 1
          fi

          # Build binary
          if [ "${{ matrix.goarch }}" = "arm" ]; then
            GOARM=${{ matrix.goarm }} go build -v -o "bin/${BINARY_NAME}" cmd/webpanel/main.go
          else
            go build -v -o "bin/${BINARY_NAME}" cmd/webpanel/main.go
          fi

          # Create checksums
          sha256sum "bin/${BINARY_NAME}" > "bin/${BINARY_NAME}.sha256"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 #Updated to v4
        with:
          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}-${{ matrix.goarm }}
          path: bin/
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') # Only run for tags
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v4
        with:
          path: release_bin
          
      - name: Get the version
        id: get_version
        run: echo "version=$(echo ${GITHUB_REF#refs/tags/v})" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: Release ${{ steps.get_version.outputs.version }}
          body: |
            Binaries for this release are attached below.
          artifacts: "release_bin/*" # now we upload the content of the release_bin.
          token: ${{ secrets.GITHUB_TOKEN }}
